---
- name: Update apt packages
  become: yes
  apt:
    update_cache: yes

- name: install virtualbox packages
  become: yes
  with_items: "{{ virtualbox_packages }}"
  apt:
    pkg: "{{ item.name }}"
    state: latest

