---
- name: Update packages
  become: yes
  package:
    update_cache: yes

- name: install virtualbox packages
  become: yes
  with_items: "{{ ubuntu_virtualbox_packages }}"
  package:
    pkg: "{{ item.name }}"
    state: latest
