---
- name: install gui packages
  become: yes
  with_items: "{{ debian_gui_packages }}"
  package:
    pkg: "{{ item.name }}"
    state: latest

- name: configure slim
  become: yes
  template:
    src: deb-slim.conf.j2
    dest: /etc/slim.conf

- name: configure trackpoint in X
  become: yes
  template:
    src: deb-20-thinkpad.conf.j2
    dest: /usr/share/X11/xorg.conf.d/20-thinkpad.conf
    owner: root
    group: root

    #- name: install gui testing packages
    #  become: yes
    #  with_items: "{{ gui_testing_packages }}"
    #  package:
    #    pkg: "{{ item.name }}"
    #    default_release: "buster"
    #    state: latest
