---
debian_util_packages:
  - name: fakeroot
  - name: keepassxc
  - name: pv
  - name: pwgen
  - name: silversearcher-ag
  - name: strace
  - name: suckless-tools
  - name: sysstat
  - name: unp
  - name: unzip
  - name: wajig

ubuntu_util_packages:
  - name: fakeroot
  - name: keepassxc
  - name: pv
  - name: pwgen
  - name: silversearcher-ag
  - name: strace
  - name: suckless-tools
  - name: sysstat
  - name: unp
  - name: unzip
  - name: wajig

fedora_util_packages:
  - name: fakeroot
  - name: keepassxc
  - name: pv
  - name: pwgen
  - name: strace
  - name: sysstat
  - name: unzip

freebsd_util_packages:
  - name: keepassxc
  - name: inotify-tools
  - name: pv
  - name: the_silver_searcher
  - name: unzip
  - name: py37-markupsafe

