---

audio_packages:
  - name: audacious
  - name: alsa-tools
  - name: alsa-tools-gui
  - name: alsa-utils
  - name: dbus-x11
  - name: jack-tools
  - name: ladish
  - name: laditools
  - name: ncmpcpp
  - name: normalize-audio
  - name: pulseaudio-module-jack
  - name: python3-xdg
  - name: sox
  - name: sweep

audio_backports_packages:
  - name: linux-headers-rt-amd64
  - name: linux-image-rt-amd64
