---
- name: install communication packages
  become: yes
  with_items: "{{ communication_packages }}"
  apt:
    pkg: "{{ item.name }}"
    state: latest

    #- name: install communication stretch packages
    #  become: yes
    #  with_items: "{{ communication_stretch_packages }}"
    #  apt:
    #    pkg: "{{ item.name }}"
    #    default_release: stretch
    #    state: latest

- name: install ca certs
  become: yes
  with_items: "{{ communication_certs }}"
  get_url:
    url: "{{ item.url }}/{{ item.filename }}"
    dest: "/usr/local/share/ca-certificates/{{ item.filename }}"
    mode: 0644

- name: update certificates
  become: yes
  shell: update-ca-certificates
