---
- name: install video packages
  become: yes
  with_items: "{{ ubuntu_video_packages }}"
  package:
    pkg: "{{ item.name }}"
    state: latest

- name: install video packages
  become: yes
  with_items: "{{ ubuntu_video_packages }}"
  package:
    pkg: "{{ item.name }}"
    state: latest
