---
- name: install develop packages
  become: yes
  with_items: "{{ debian_develop_packages }}"
  package:
    pkg: "{{ item.name }}"
    state: latest

- name: install develop buster packages
  become: yes
  with_items: "{{ debian_develop_buster_packages }}"
  package:
    pkg: "{{ item.name }}"
    state: latest
