---
- name: install develop packages
  become: yes
  with_items: "{{ develop_packages }}"
  apt:
    pkg: "{{ item.name }}"
    state: latest

- name: install develop buster packages
  become: yes
  with_items: "{{ develop_buster_packages }}"
  apt:
    pkg: "{{ item.name }}"
    default_release: "buster"
    state: latest

    #
    #- name: install develop testing packages
    #  become: yes
    #  with_items: "{{ develop_testing_packages }}"
    #  apt:
    #    pkg: "{{ item.name }}"
    #    default_release: "buster"
    #    state: latest
