---
- name: install develop packages
  become: yes
  with_items: "{{ ubuntu_develop_packages }}"
  package:
    pkg: "{{ item.name }}"
    state: latest

- name: install develop bionic packages
  become: yes
  with_items: "{{ ubuntu_develop_bionic_packages }}"
  package:
    pkg: "{{ item.name }}"
    default_release: "bionic"
    state: latest
