---
- name: install develop packages
  become: yes
  with_items: "{{ ubuntu_develop_packages }}"
  package:
    pkg: "{{ item.name }}"
    state: latest

- name: install develop focal packages
  become: yes
  with_items: "{{ ubuntu_develop_focal_packages }}"
  package:
    pkg: "{{ item.name }}"
    default_release: "focal"
    state: latest
