---
develop_packages:
  - name: cmake
  - name: exuberant-ctags
  - name: libjpeg-dev
  - name: libssl-dev
  - name: python3-dev
  - name: python3-pip
  - name: ruby
  - name: tmux
  - name: vim
  - name: zlib1g-dev
  - name: virtualbox

develop_buster_packages:
  - name: nodejs

develop_repositories:
  - name: nodejs
    key: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
